### ISSUE TITLE
Create the mvp

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/codesharingplatform.net#1]
I'm going to refactor my Spring Code Sharing Platform project using ASP.NET, Razor, C# and Sqlite.

# TODOs

- [x] Add the DataContext
- [x] Create the Entity Models
- [x] Add the web project (razor pages)
- [x] Add the webapi
- [x] Add the unit tests (for entity models)
- [x] Add a README
- [x] Add an sln file
